/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2026-01-29 14:20:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Event Management System</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .subtitle {\r\n");
      out.write("            color: #999;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            border: 2px solid #e0e0e0;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: border-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"]:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #667eea;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: transform 0.2s, box-shadow 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 5px 20px rgba(102, 126, 234, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:active {\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .events-list {\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            padding-top: 30px;\r\n");
      out.write("            border-top: 2px solid #f0f0f0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .events-list h2 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .event-item {\r\n");
      out.write("            background: #f9f9f9;\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border-left: 4px solid #667eea;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .success-message {\r\n");
      out.write("            background: #d4edda;\r\n");
      out.write("            color: #155724;\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            display: none;\r\n");
      out.write("            border: 1px solid #c3e6cb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .success-message.show {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loading {\r\n");
      out.write("            display: none;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #53619c;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1>Event Manager</h1>\r\n");
      out.write("        <p class=\"subtitle\">Create and manage your events effortlessly</p>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"success-message\" id=\"successMsg\"></div>\r\n");
      out.write("\r\n");
      out.write("    <form id=\"eventForm\">\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"title\">Event Title</label>\r\n");
      out.write("            <input type=\"text\" name=\"title\" id=\"title\" placeholder=\"Enter event title...\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button type=\"submit\">\r\n");
      out.write("            <span>+ Add Event</span>\r\n");
      out.write("            <span class=\"loading\" id=\"loading\">Adding...</span>\r\n");
      out.write("        </button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"events-list\" id=\"eventsList\" style=\"display: none;\">\r\n");
      out.write("        <h2> Recent Events</h2>\r\n");
      out.write("        <div id=\"eventsContainer\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("let events = [];\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"eventForm\").addEventListener(\"submit\", function(e){\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("    const title = document.getElementById(\"title\").value.trim();\r\n");
      out.write("    const loading = document.getElementById(\"loading\");\r\n");
      out.write("    const successMsg = document.getElementById(\"successMsg\");\r\n");
      out.write("\r\n");
      out.write("    if(title === \"\"){\r\n");
      out.write("        alert(\"Please enter an event title!\");\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    loading.style.display = \"inline\";\r\n");
      out.write("\r\n");
      out.write("    fetch(\"addevent\", {\r\n");
      out.write("        method: \"POST\",\r\n");
      out.write("        body: new FormData(this)\r\n");
      out.write("    })\r\n");
      out.write("    .then(response => response.text())\r\n");
      out.write("    .then(data => {\r\n");
      out.write("        loading.style.display = \"none\";\r\n");
      out.write("        \r\n");
      out.write("        // Show success message\r\n");
      out.write("        successMsg.textContent = data;\r\n");
      out.write("        successMsg.classList.add(\"show\");\r\n");
      out.write("        \r\n");
      out.write("        // Add to events list\r\n");
      out.write("        events.unshift(title);\r\n");
      out.write("        updateEventsList();\r\n");
      out.write("        \r\n");
      out.write("        // Clear form\r\n");
      out.write("        document.getElementById(\"title\").value = \"\";\r\n");
      out.write("        \r\n");
      out.write("        // Hide success message after 3 seconds\r\n");
      out.write("        setTimeout(() => {\r\n");
      out.write("            successMsg.classList.remove(\"show\");\r\n");
      out.write("        }, 3000);\r\n");
      out.write("    })\r\n");
      out.write("    .catch(error => {\r\n");
      out.write("        loading.style.display = \"none\";\r\n");
      out.write("        alert(\"Error: \" + error);\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function updateEventsList() {\r\n");
      out.write("    const eventsList = document.getElementById(\"eventsList\");\r\n");
      out.write("    const eventsContainer = document.getElementById(\"eventsContainer\");\r\n");
      out.write("    \r\n");
      out.write("    if(events.length > 0) {\r\n");
      out.write("        eventsList.style.display = \"block\";\r\n");
      out.write("        eventsContainer.innerHTML = events.map((event, index) => \r\n");
      out.write("            `<div class=\"event-item\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('.');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>`\r\n");
      out.write("        ).join(\"\");\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
